
name: Deploy Pelican Site to GitHub Pages

on:
  push:
    branches: [ source ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Build site
        run: |
          pelican content -o output -s publishconf.py
          
      - name: Check generated files
        run: |
          echo "Checking generated output..."
          ls -la output/
          echo "Checking for images..."
          ls -la output/images/ || echo "No images directory found!"
          echo "Checking categories..."
          ls -la output/category/ || echo "No category directory found!"

      - name: Deploy to GitHub Pages
        run: |
          # Create a fresh, empty master branch
          git checkout --orphan temp_master
          
          # Remove all files from staging
          git rm -rf --cached .
          
          # Add only the contents of the output directory
          cp -r output/* .
          
          # Create .nojekyll file to disable Jekyll processing
          touch .nojekyll
          
          # Stage the changes
          git add .
          
          # Commit the changes
          git commit -m "Deploy site $(date +'%Y-%m-%d %H:%M:%S')"
          
          # Force push to master branch
          git push -f origin temp_master:master
          
          echo "Site successfully deployed to master branch!"