name: Build & Deploy Pelican Site

on:
  push:
    branches: [ source ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source & submodules
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install invoke pelican ghp-import

      - name: Build & publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: invoke publish
