name: Build & Deploy Pelican Site

on:
  push:
    branches: [ source ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source & submodules
        uses: actions/checkout@v4
        with:
          ref: source
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install invoke pelican ghp-import markdown

      - name: Build & publish with Invoke
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: invoke publish
