name: Build & Publish Site

on:
  push:
    branches: [ source ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source & theme submodules
        uses: actions/checkout@v4
        with:
          ref: source
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          fetch-depth: 0
          persist-credentials: true  # ensure subsequent pushes use the token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install invoke pelican ghp-import

      - name: Build & Publish via Invoke
        run: invoke publish   # inside, ghp-import will push for us
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
